import type { StockRow } from "@/features/inventory-shared";
import { PRODUCT_PLACEHOLDER_IMAGE } from "@/features/inventory-shared";

export const sandaliasInventory: StockRow[] = [
  {
    id: 1,
    model: "Sandalia Casual S-001",
    color: "Negro",
    size1: { size: 36, qty: 5 },
    size2: { size: 37, qty: 2 },
    size3: { size: 38, qty: 2 },
    totalPairs: 9,
    season: "Verano 2024",
    status: "Activo",
    image: PRODUCT_PLACEHOLDER_IMAGE,
    provider: "Calzados Mila SAC",
    soldTotal: 28,
  },
  {
    id: 2,
    model: "Sandalia Casual S-001",
    color: "Marron",
    size1: { size: 36, qty: 4 },
    size2: { size: 37, qty: 6 },
    size3: { size: 38, qty: 4 },
    totalPairs: 14,
    season: "Verano 2024",
    status: "Activo",
    image: PRODUCT_PLACEHOLDER_IMAGE,
    provider: "Calzados Mila SAC",
    soldTotal: 41,
  },
  {
    id: 3,
    model: "Sandalia Sport S-002",
    color: "Azul",
    size1: { size: 39, qty: 2 },
    size2: { size: 40, qty: 3 },
    size3: { size: 41, qty: 5 },
    totalPairs: 10,
    season: "Verano 2024",
    status: "Activo",
    image: PRODUCT_PLACEHOLDER_IMAGE,
    provider: "Distribuidora Andina",
    soldTotal: 32,
  },
  {
    id: 4,
    model: "Sandalia Sport S-002",
    color: "Gris",
    size1: { size: 39, qty: 1 },
    size2: { size: 40, qty: 0 },
    size3: { size: 41, qty: 2 },
    totalPairs: 3,
    season: "Verano 2024",
    status: "Bloqueado",
    image: PRODUCT_PLACEHOLDER_IMAGE,
    provider: "Distribuidora Andina",
    soldTotal: 19,
  },
];
